compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

defaultSemverRangePrefix: ""

enableConstraintsChecks: true

enableProgressBars: false

enableTelemetry: false

httpRetry: 5

logFilters:
  - level: warning
